version: '3.1'
services:
  db:
    image: mysql:5.7
    ports:
      - 3308:3306
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: social_contract_development
    volumes:
      - mysql_volume:/var/lib/mysql
  texlive:
    image: nontan18/texlive:stable
    command: latexmk --pvc ./index.tex
    volumes: 
      - ./paper/src:/root/work
volumes:
  mysql_volume:
    driver: local